//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public System.Guid UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNo { get; set; }
        public string ProfilePicture { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public int UserRoleID { get; set; }
    }
}
